#!/usr/bin/php
<?php
/**
 * Minify 1.0 - Copyright (c) 2015-2016 Infotoo International Limited - http://www.infotoo.com (MIT License)
 *
 * Last updated: 2016-05-06
 */

/*
 * The MIT license
 *
 * Copyright (C) 2015 Infotoo International Limited
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

#default copyright message
define('TXT_COPYRIGHT', '/'.'* Copyright (c) Infotoo International Limited - http://www.infotoo.com - Updated: '.date('Y-m-d').' *'.'/'."\r\n");

#path to Line Marco
define('BIN_LINE_MACRO', '/home/bin/line-macro');

#path to Less pre-processor
define('BIN_LESSC', '/home/bin/lessc');

#path to Java binary'
define('BIN_JAVA', '/usr/bin/java');

#path to YUI Compressor
define('BIN_YUI_COMPRESSOR', '/home/lib/yuicompressor/yuicompressor-2.4.8.jar');

#path to Gzip Minimized
define('BIN_GZIP_MINIMIZED', '/home/bin/gzip-minimized');

#================================= implementation =================================

if ( count($argv)<2 )
{
	echo 'Usage:  minify  FILENAME	[-skip-macro]  [-skip-less]	 [-skip-min]  [-skip-gzip]	[-skip-delete]	[-outdir=output_dir]'."\n";
	exit;
}

if ( !file_exists($argv[1]) )
{
	echo '"'.$argv[1].'" not exists'."\n";
	exit;
}
$match = null;
if ( !preg_match('/\.(css|js|less)$/',$argv[1],$match) )
{
	echo '"'.$argv[1].'" file extension is not "css/js/less".'."\n";
	exit;
}
$file_source = $argv[1];
$file_ext = $match[1];

$SKIP_MACRO = false;
$SKIP_LESS = false;
$SKIP_MIN = false;
$SKIP_GZIP = false;
$SKIP_DELETE_FILE = false;
$outdir = null;
foreach ( $argv as $argvs )
{
	if ( preg_match('/^-{1,2}skip-macro$/', $argvs) )
	{
		$SKIP_MACRO = true;
		continue;
	}
	if ( preg_match('/^-{1,2}skip-less$/', $argvs) )
	{
		$SKIP_LESS = true;
		continue;
	}
	if ( preg_match('/^-{1,2}skip-min$/', $argvs) )
	{
		$SKIP_MIN = true;
		continue;
	}
	if ( preg_match('/^-{1,2}skip-gzip$/', $argvs) )
	{
		$SKIP_GZIP = true;
		continue;
	}	 if ( preg_match('/^-{1,2}skip-delete$/', $argvs) )
	{
		$SKIP_DELETE_FILE = true;
		continue;
	}	 $find = null;
	if ( preg_match('/^-{1,2}outdir=(.*)$/', $argvs, $find) )
	{
		$outdir = $find[1];
		continue;
	}
}

#prepare files name
if ( $file_source == basename($file_source) )
{
	$file_source = './'.$file_source;
}
switch ( $file_ext )
{
	case 'css':
		$minize_type = 'css';
		break;
	case 'js':
		$minize_type = 'js';
		$SKIP_LESS = true;
		break;

	case 'less':
		$minize_type = 'css';
		$SKIP_MACRO = true;
		break;

}
$filename_prefix = preg_replace('/\.'.$file_ext.'$/', '', $file_source );
$file_macro_applied = $filename_prefix.'.macro.'.$minize_type;
$file_processed = $filename_prefix.'.raw.'.$minize_type;
$file_minimized = $filename_prefix.'.min.'.$minize_type;

#get copyright declaration
function get_copyright( $f )
{
	$s = file_get_contents( $f );
	if ( preg_match('/'.'^\/\*[\*!](?:.|\r|\n)*?\*\/(\r|\n)+'.'/', $s, $m) )
	{
		return (substr($m[0],0,3) == '/*!')? '' : $m[0];
	}
	return TXT_COPYRIGHT;
}
$copyright = get_copyright( $file_source );

#run Line Marco, if needed
if ( !$SKIP_MACRO )
{
	system( BIN_LINE_MACRO.' '.escapeshellarg($file_source).' '.escapeshellarg($file_macro_applied) );
}
else
{
	copy( $file_source, $file_macro_applied );
}

#run less, if needed
if ( !$SKIP_LESS )
{
	system( BIN_LESSC.' '.escapeshellarg($file_macro_applied).' '.escapeshellarg($file_processed) );
	unlink( $file_macro_applied );
}
else
{
	rename( $file_macro_applied, $file_processed );
}

#minimize file
if ( !$SKIP_MIN )
{
	system( BIN_JAVA.' -jar '.BIN_YUI_COMPRESSOR.' --type '.$minize_type.' -o '.escapeshellarg($file_minimized).' '.escapeshellarg($file_processed) );
}
else
{
	copy( $file_processed, $file_minimized );
}

#insert copyright
file_put_contents( $file_minimized, $copyright.file_get_contents($file_minimized) );

#run Gzip Minimized
if ( !$SKIP_GZIP )
{
	system( BIN_GZIP_MINIMIZED.' '.$file_minimized);
}

#delete interminiate files
if ( !$SKIP_DELETE_FILE )
{
	unlink( $file_processed );
}

#move to output folder
if ( $outdir != null )
{
	system('mv '.escapeshellarg($file_minimized).' '.escapeshellarg($outdir) );
	if ( !$SKIP_GZIP )
	{
		system('mv '.escapeshellarg($file_minimized.'.gz').' '.escapeshellarg($outdir) );
	}
}

